name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: setup node
        uses: actions/setup-node@v2.1.5

      - name: install node packages
        run: |
          npm i bignumber.js
          npm i tweetnacl
          npm i tweetnacl-util
          npm i express
          npm i body-parser
          npm i ws
          npm i node-fetch
          sudo npm i -g wallet

      - name: install python packages
        run: |
          pip install requests

      - name: execute python script
        working-directory: ./tests
        run: python test.py
